# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/mizix/BX/CSE305/cse305-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/mizix/BX/CSE305/cse305-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mizix/BX/CSE305/cse305-project/CMakeFiles /Users/mizix/BX/CSE305/cse305-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/mizix/BX/CSE305/cse305-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named seq_shortest_path

# Build rule for target.
seq_shortest_path: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 seq_shortest_path
.PHONY : seq_shortest_path

# fast build rule for target.
seq_shortest_path/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/build
.PHONY : seq_shortest_path/fast

#=============================================================================
# Target rules for targets named graph_gen

# Build rule for target.
graph_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graph_gen
.PHONY : graph_gen

# fast build rule for target.
graph_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/build
.PHONY : graph_gen/fast

src/deltastep_seq.o: src/deltastep_seq.cpp.o
.PHONY : src/deltastep_seq.o

# target to build an object file
src/deltastep_seq.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/deltastep_seq.cpp.o
.PHONY : src/deltastep_seq.cpp.o

src/deltastep_seq.i: src/deltastep_seq.cpp.i
.PHONY : src/deltastep_seq.i

# target to preprocess a source file
src/deltastep_seq.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/deltastep_seq.cpp.i
.PHONY : src/deltastep_seq.cpp.i

src/deltastep_seq.s: src/deltastep_seq.cpp.s
.PHONY : src/deltastep_seq.s

# target to generate assembly for a file
src/deltastep_seq.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/deltastep_seq.cpp.s
.PHONY : src/deltastep_seq.cpp.s

src/graph.o: src/graph.cpp.o
.PHONY : src/graph.o

# target to build an object file
src/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/graph.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/src/graph.cpp.o
.PHONY : src/graph.cpp.o

src/graph.i: src/graph.cpp.i
.PHONY : src/graph.i

# target to preprocess a source file
src/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/graph.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/src/graph.cpp.i
.PHONY : src/graph.cpp.i

src/graph.s: src/graph.cpp.s
.PHONY : src/graph.s

# target to generate assembly for a file
src/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/graph.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/src/graph.cpp.s
.PHONY : src/graph.cpp.s

src/graph_gen.o: src/graph_gen.cpp.o
.PHONY : src/graph_gen.o

# target to build an object file
src/graph_gen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/graph_gen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/src/graph_gen.cpp.o
.PHONY : src/graph_gen.cpp.o

src/graph_gen.i: src/graph_gen.cpp.i
.PHONY : src/graph_gen.i

# target to preprocess a source file
src/graph_gen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/graph_gen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/src/graph_gen.cpp.i
.PHONY : src/graph_gen.cpp.i

src/graph_gen.s: src/graph_gen.cpp.s
.PHONY : src/graph_gen.s

# target to generate assembly for a file
src/graph_gen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/graph_gen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/src/graph_gen.cpp.s
.PHONY : src/graph_gen.cpp.s

src/seq_shortest_path.o: src/seq_shortest_path.cpp.o
.PHONY : src/seq_shortest_path.o

# target to build an object file
src/seq_shortest_path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/seq_shortest_path.cpp.o
.PHONY : src/seq_shortest_path.cpp.o

src/seq_shortest_path.i: src/seq_shortest_path.cpp.i
.PHONY : src/seq_shortest_path.i

# target to preprocess a source file
src/seq_shortest_path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/seq_shortest_path.cpp.i
.PHONY : src/seq_shortest_path.cpp.i

src/seq_shortest_path.s: src/seq_shortest_path.cpp.s
.PHONY : src/seq_shortest_path.s

# target to generate assembly for a file
src/seq_shortest_path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/src/seq_shortest_path.cpp.s
.PHONY : src/seq_shortest_path.cpp.s

test_generate_graph.o: test_generate_graph.cpp.o
.PHONY : test_generate_graph.o

# target to build an object file
test_generate_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/test_generate_graph.cpp.o
.PHONY : test_generate_graph.cpp.o

test_generate_graph.i: test_generate_graph.cpp.i
.PHONY : test_generate_graph.i

# target to preprocess a source file
test_generate_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/test_generate_graph.cpp.i
.PHONY : test_generate_graph.cpp.i

test_generate_graph.s: test_generate_graph.cpp.s
.PHONY : test_generate_graph.s

# target to generate assembly for a file
test_generate_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graph_gen.dir/build.make CMakeFiles/graph_gen.dir/test_generate_graph.cpp.s
.PHONY : test_generate_graph.cpp.s

test_seq_shortest_path.o: test_seq_shortest_path.cpp.o
.PHONY : test_seq_shortest_path.o

# target to build an object file
test_seq_shortest_path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/test_seq_shortest_path.cpp.o
.PHONY : test_seq_shortest_path.cpp.o

test_seq_shortest_path.i: test_seq_shortest_path.cpp.i
.PHONY : test_seq_shortest_path.i

# target to preprocess a source file
test_seq_shortest_path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/test_seq_shortest_path.cpp.i
.PHONY : test_seq_shortest_path.cpp.i

test_seq_shortest_path.s: test_seq_shortest_path.cpp.s
.PHONY : test_seq_shortest_path.s

# target to generate assembly for a file
test_seq_shortest_path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq_shortest_path.dir/build.make CMakeFiles/seq_shortest_path.dir/test_seq_shortest_path.cpp.s
.PHONY : test_seq_shortest_path.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... graph_gen"
	@echo "... seq_shortest_path"
	@echo "... src/deltastep_seq.o"
	@echo "... src/deltastep_seq.i"
	@echo "... src/deltastep_seq.s"
	@echo "... src/graph.o"
	@echo "... src/graph.i"
	@echo "... src/graph.s"
	@echo "... src/graph_gen.o"
	@echo "... src/graph_gen.i"
	@echo "... src/graph_gen.s"
	@echo "... src/seq_shortest_path.o"
	@echo "... src/seq_shortest_path.i"
	@echo "... src/seq_shortest_path.s"
	@echo "... test_generate_graph.o"
	@echo "... test_generate_graph.i"
	@echo "... test_generate_graph.s"
	@echo "... test_seq_shortest_path.o"
	@echo "... test_seq_shortest_path.i"
	@echo "... test_seq_shortest_path.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

